In [3]:
import scipy as sc
import numpy as np
array1 = np.array ([(1,2,3)])
print (array1)

[[1 2 3]]


In [5]:
array2=np.linspace(0,10,5)
print(array2,'\n')
array22=np.linspace(0,1,3)
print(array22,'\n')

[ 0.   2.5  5.   7.5 10. ] 

[0.  0.5 1. ] 



In [8]:
array3=np . arange (0 ,10 ,1) 
print( array3 ,'\n')
array4=np.arange(0,5,0.5)
print(array4,'\n')
array44=np.arange(5)
print(array,'\n')
print(np.arange(10),'\n')

[0 1 2 3 4 5 6 7 8 9] 

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5] 

[[1 2 3]] 

[0 1 2 3 4 5 6 7 8 9] 



In [9]:
array5 = np . zeros (5) 
print ( array5 ,'\n')
array6=np.ones(3)
print(array6,'\n')

[0. 0. 0. 0. 0.] 

[1. 1. 1.] 



In [16]:
array7=np.linspace(-2,3,6)
print(array7,'\n')
print(array7+2,'\n')
print(array7-1,'\n')
print(array7*3,'\n')
print(array7 / 2,'\n')
print(array7**4,'\n')
print((array7+2)*5,'\n')
print(np.sin(array),'\n')
print(np.cos(array7),'\n')

[-2. -1.  0.  1.  2.  3.] 

[0. 1. 2. 3. 4. 5.] 

[-3. -2. -1.  0.  1.  2.] 

[-6. -3.  0.  3.  6.  9.] 

[-1.  -0.5  0.   0.5  1.   1.5] 

[16.  1.  0.  1. 16. 81.] 

[ 0.  5. 10. 15. 20. 25.] 

[[0.84147098 0.90929743 0.14112001]] 

[-0.41614684  0.54030231  1.          0.54030231 -0.41614684 -0.9899925 ] 



In [20]:
array8 = np.array([10,20,30])
array9 = np.array([50 ,60 ,70])
result1=array8+array9 
print(result1,'\n')
print(array9-array8,'\n')
print(array8-array9,'\n')
print(array8*array9,'\n')
print(array9/array8,'\n')

[ 60  80 100] 

[40 40 40] 

[-40 -40 -40] 

[ 500 1200 2100] 

[5.         3.         2.33333333] 



In [21]:
array10=np.array([[1,2,3] ,[4,5,6]])
print(array10,'\n')
array11=np.array([[1,1,1],[2,2,2],[3,3,3]])
print(array11,'\n')

[[1 2 3]
 [4 5 6]] 

[[1 1 1]
 [2 2 2]
 [3 3 3]] 



In [22]:
array12=np.array([np.eye(3)])
print(array12,'\n')

[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]] 



In [30]:
array13=np.arange(8)
print(array13,'\n')
array14=np.reshape(array13,(2,4))
print(array14,'\n')
print(np.reshape(array13,(4,2)),'\n')
print(np.reshape(np.arange(8),(4,2)),'\n')
print(np.reshape(array13,(2,4)),'\n')


[0 1 2 3 4 5 6 7] 

[[0 1 2 3]
 [4 5 6 7]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]] 

[[0 1 2 3]
 [4 5 6 7]] 



In [31]:
array15=np.array([[1,4,5],[2,3,6]])
print(array15,'\n')
print(array15+2,'\n')
print(array15-3,'\n')
print(array15*5,'\n')
print(2/array15**3,'\n')
print(np.cos(array15),'\n')


[[1 4 5]
 [2 3 6]] 

[[3 6 7]
 [4 5 8]] 

[[-2  1  2]
 [-1  0  3]] 

[[ 5 20 25]
 [10 15 30]] 

[[2.         0.03125    0.016     ]
 [0.25       0.07407407 0.00925926]] 

[[ 0.54030231 -0.65364362  0.28366219]
 [-0.41614684 -0.9899925   0.96017029]] 



In [9]:
import scipy as sc
import numpy as np
array16=np.array([[1.,2.,3.],[4.,5.,6.]])
print(array16,'\n')
array17=np.array([[-1.,-2.,-3],[-4.,-5.,-6.]])
print(array17,'\n')
array16*array17
print(np.dot(array16,array17),'\n')

[[1. 2. 3.]
 [4. 5. 6.]] 

[[-1. -2. -3.]
 [-4. -5. -6.]] 



ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [6]:
import scipy as sc
import numpy as np 
array18=sc.rand(8)
print(np.array(np.reshape((array18),(2,4))),'\n')
array19=print(np.array(np.reshape((sc.rand(8)),(2,4))),'\n') 

[[0.9948242  0.01975596 0.83959497 0.16676705]
 [0.98975371 0.4628888  0.23619722 0.82138397]] 

[[0.90614087 0.29231278 0.37280568 0.98879703]
 [0.4014683  0.64201982 0.39506918 0.19986556]] 



In [8]:
import scipy as sc
import numpy as np 
array20=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array20,'\n')
print(array20[0,:],'\n')
print(array20[1,:],'\n')
print(array20[2,:],'\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3] 

[4 5 6] 

[7 8 9] 

